services:
  gitsight-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./gource_videos:/gource_videos
    depends_on:
      - redis
    environment:
      - REDIS_URL=${REDIS_URL}

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

volumes:
  gource_videos:
  redis_data:
