services:
  gitsight-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT:-8081}:8081"
    volumes:
      - ./gource_videos:/gource_videos
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

volumes:
  gource_videos:
  redis_data:
