[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
url = "2.2"
tempfile = "3.2"
tokio = { version = "1.0", features = ["full"] }
